### PR TITLE
Removing Auto from generated resource files

### PR DESCRIPTION
**Pull request by paganotoni**
Removes Auto from generated resources. #12

### CODE REVIEW

**Comment by kteb** [comment]
Shouldn't we have a configuration value that shows what we want to have, by default it should be r.HTML but could r.Auto or r.JSON ?

**Comment by paganotoni** [comment]
We talked about removing `Auto` and leave it as an optional thing in case someone wants to use it (maybe an external library?). However now that you mention this I notice this PR still needs to handle JSON generated resource as it changes resources to only work HTML. 🤔

**Comment by stanislas-m** [comment]
Agreed, the aim was to remove all the `Auto` magic. Maybe we can use something more explicit, like https://github.com/gobuffalo/x/tree/master/responder?

**Comment by paganotoni** [comment]
@stanislas-m ended up using .AsWeb and .AsAPI to identify which ones to generate. Thoughts?

**Comment by stanislas-m** [comment]
@paganotoni I liked the previous commit more. :)
In the new version the decision is made at compilation time, while the current `Auto` method works at run time. With `Auto` the app was able to render JSON, XML and HTML, while here you'll only have JSON or HTML.

I think the one from your previous commit was almost fine, but maybe you should have XML/JSON for `AsAPI`, and HTML for `AsWeb` (not sure if JSON/XML is needed here). Thoughts?

**Review by stanislas-m — COMMENTED** [review]
LGTM. I just want to test it a bit before giving the approval. :)

**Comment by paganotoni** [comment]
thanks @stanislas-m

**Review by stanislas-m — APPROVED** [review]

**Review by mclark4386 — APPROVED** [review]
very nice^^

**Pull request merged**
